/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppToolBar: typeof import('./components/common/AppToolBar.vue')['default']
    MyChatMessage: typeof import('./components/chat/MyChatMessage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SessionList: typeof import('./components/chat/SessionList.vue')['default']
  }
}
