/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AdminLeftMenu: typeof import('./components/admin/AdminLeftMenu.vue')['default']
    AdminPage: typeof import('./components/admin/AdminPage.vue')['default']
    AdminSectionCard: typeof import('./components/admin/AdminSectionCard.vue')['default']
    AdminToolBar: typeof import('./components/admin/AdminToolBar.vue')['default']
    AppToolBar: typeof import('./components/common/AppToolBar.vue')['default']
    ComplainDialog: typeof import('./components/chat/ComplainDialog.vue')['default']
    DetailView: typeof import('./components/common/DetailView.vue')['default']
    Popoto: typeof import('./components/common/Popoto.vue')['default']
    ProgressCard: typeof import('./components/dashboard/ProgressCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SessionList: typeof import('./components/chat/SessionList.vue')['default']
    UIConfig: typeof import('./components/common/UIConfig.vue')['default']
    WordCloud: typeof import('./components/dashboard/WordCloud.vue')['default']
  }
}
